### ISSUE TITLE
Switch to OpenAPI File Generation

### ISSUE THREAD

**Issue by berndruecker** [camunda-community-hub/camunda-operate-client-java#2]
See https://camunda.slack.com/archives/C9B5270DA/p1665998954761439

It's all hand written code for now. It also brings the different auth mechanisms for SaaS and SM
the Tasklist client is generated but not the Operate

Is there a reason why hand-written? If it has to be that way - maybe there is no point providing the open API file as I requested 

Operate API used by the UI are very complete compared to the one exposed on SaaS
The Operate Client has a "beta" version for undocumented APIs that can be used in a SM environment

but it would be better to generate a client from an open API file

**Comment by falko** [comment]
The internal APIs are closed since 8.0.2. So that beta client code can probably be deleted.


________________________________
From: Bernd Ruecker ***@***.***>
Sent: Tuesday, October 18, 2022 6:50:49 PM
To: camunda-community-hub/camunda-operate-client-java ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [camunda-community-hub/camunda-operate-client-java] Switch to OpenAPI File Generation (Issue #2)


See https://camunda.slack.com/archives/C9B5270DA/p1665998954761439

It's all hand written code for now. It also brings the different auth mechanisms for SaaS and SM
the Tasklist client is generated but not the Operate

Is there a reason why hand-written? If it has to be that way - maybe there is no point providing the open API file as I requested

Operate API used by the UI are very complete compared to the one exposed on SaaS
The Operate Client has a "beta" version for undocumented APIs that can be used in a SM environment

but it would be better to generate a client from an open API file

**Comment by chDame** [comment]
@falko, even in SM ?

**Comment by falko** [comment]
Okay, maybe in self-managed it could still work but we should raise a product gap every time we need to employ this workaround.


________________________________

**Comment by berndruecker** [comment]
We might get a properly generated OpenAPI.json some time https://github.com/camunda/product-gaps/issues/47

Anybody have some time to look into this by chance to auto-generate from OpenAPI by chance?

**Comment by chDame** [comment]
Sure, I could try to have a look into it by the end of the week of beginning of next week

**Comment by jonathanlukas** [comment]
As this project will only be maintained for backwards-compatibility reasons, there is no need to switch the implementation.
