### ISSUE TITLE
Support API methods

### ISSUE THREAD

**Issue by NewbieProger** [camunda-community-hub/camunda-operate-client-java#27]
Why u made lib just with search'es an DTO's without any other API endpoints like 'delete processes' and just gave us `.execute()` method for api requests?

**Comment by chDame** [comment]
Hi @NewbieProger,

To answer your question "why I made this library", the answer is because it was required for my projects. You're free to use it or not.
Now, if you're missing any feature like deleteProcessInstance(Long key), you should or create an issue explaining what you would expect or create a Pull Request. If you're globally not satisfied by the library design, please feel free to create another library that could be beneficial for the whole community.

Hope that helps :)
